### ISSUE TITLE
JupyterHub: Bring your own image

### ISSUE THREAD

**Issue by sebastian-luna-valero** [pangeo-data/pangeo-eosc#96]
As discussed in https://github.com/pangeo-data/pangeo-eosc/issues/93#issuecomment-2769488079

Let's explore: https://2i2c.org/community-showcase/user/howto/specify-unlisted-image.html#specify-your-own-image-for-the-software-environment

**Comment by rsignell** [comment]
I tested this out recently on one of the 2i2c-supported hubs, so I'm wondering if @jmunroe or someone else from the 2i2c team might be able to help us out?

**Comment by jmunroe** [comment]
Thanks for the tag @rsignell .  I am really keen to ensure that workflows are portable between different JupyterHub deployment whether managed by 2i2c or not. 

This also gives me a bit an excuse to poke around pangeo-eosc which I hadn't previously had a reason to work with.

It might be as simple as adding

```
            unlisted_choice:
              enabled: True
              display_name: "Custom image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available docker image, of form <image-name>:<tag>"
              kubespawner_override:
                image: "{value}"
```

to the `profilelist` in https://github.com/pangeo-data/pangeo-eosc/blob/main/providers/kubernetes/daskhub.yaml

This may or may not depend on the particular version of the helm charts that pangeo-eosc are using (I am a Iittle out of my area of expertise here to recognize right away how your infrastructure is configured)

I'm away for a couple of days but if this requires more follow up I'll check back next week.
